# -*- coding: utf-8 -*-
"""MILESTONE1B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MkDsXzqOtMfDwbWagTUC1-iXfhFklyuK
"""

!pip install PyYAML==5.4.1

import yaml
from yaml.loader import SafeLoader
import logging

with open('Milestone1B.yaml') as f:
    data1 = yaml.load(f, Loader= SafeLoader)
    print(data1)

res=list(data1.keys())[0]

sorted_data = yaml.dump(data1, sort_keys=True)

print(sorted_data)



logging.basicConfig(filename="Milestone1A.txt",
                    filemode='a',
                    format='%(asctime)s.00000;%(message)s ENTRY',
                    datefmt='%Y-%m-%d %H:%M:%S',
                    level=logging.INFO)
logging.info(res)